# Generated by Django 3.0.8 on 2020-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(blank='True')),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
    ]
