# Generated by Django 3.0.8 on 2020-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginuser', models.CharField(max_length=300)),
                ('keyword', models.CharField(max_length=300)),
                ('searchdate', models.DateTimeField()),
                ('searchresult', models.CharField(max_length=200)),
            ],
        ),
    ]
